server:
  servlet:
    session:
      cookie:
        name: JSESSIONID

spring:
  session:
    store-type: redis
    redis:
      namespace: shboard:session

  data:
    redis:
      host: localhost
      password: 1234
      port: 6379
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
